grafana:
  enabled: true

  admin:
    existingSecret: grafana-admin
    passwordKey: admin-password

  service:
    type: LoadBalancer

  persistence:
    enabled: true
    storageClassName: gp2
    size: 5Gi

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

prometheus:
  enabled: true

  prometheusSpec:
    retention: 2d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

  service:
    type: ClusterIP

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

alertmanager:
  enabled: true

  service:
    type: ClusterIP

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

defaultRules:
  create: true