apiVersion: v1
kind: Service
metadata:
  name: hotstar
  namespace: default
  labels:
    app: hotstar
spec:
  selector:
    app: hotstar
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
  type: {{ .Values.service.type }}
