apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: hotstar
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Shubham81772532/Capstone-DevSecOps.git
    targetRevision: main
    path: hotstar-clone/helm

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
  syncOptions:
      - CreateNamespace=true