---
- name: Setup Jenkins EC2 with DevSecOps Tools
  hosts: ubuntu
  become: yes

  roles:
    - { role: java,            tags: ["java"] }
    - { role: docker,          tags: ["docker"] }
    - { role: jenkins,         tags: ["jenkins"] }
    - { role: sonarqube,       tags: ["sonarqube"] }
    - { role: awscli,          tags: ["awscli"] }
    - { role: kubectl,         tags: ["kubectl"] }
    - { role: helm,            tags: ["helm"] }

    # Kubernetes Components
    - { role: ingress-nginx,   tags: ["ingress"] }
    - { role: metrics-server,  tags: ["metrics"] }
    - { role: monitoring,      tags: ["monitoring"] }
    - { role: argocd,          tags: ["argocd"] }

    # Verification
    - { role: verify,          tags: ["verify"] }