---
- name: Verify Java
  shell: java -version
  changed_when: false

- name: Verify Docker
  shell: docker --version
  changed_when: false

- name: Verify AWS CLI
  shell: aws --version
  changed_when: false

- name: Verify kubectl
  shell: kubectl version --client
  changed_when: false

- name: Verify Helm
  shell: helm version
  changed_when: false

- name: Verify Jenkins
  shell: systemctl is-active jenkins
  changed_when: false